/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ready"];
                    };
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ready"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics exposition or JSON snapshot */
        get: {
            parameters: {
                query?: {
                    format?: "prom" | "json";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Metrics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": components["schemas"]["MetricsSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Combined today view (meal + chores + events) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Today */
                200: {
                    headers: {
                        ETag?: string;
                        "X-Cache"?: "HIT" | "MISS";
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TodayResponse"];
                    };
                };
                /** @description Not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current week's meal plan */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weekly plan */
                200: {
                    headers: {
                        ETag?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MealsResponse"];
                    };
                };
                /** @description Not modified */
                304: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/week/{weekYear}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get meal plan for a specific ISO week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    weekYear: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Weekly plan */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MealsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a meal slot with a different recipe */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        weekYear?: string;
                        dayOfWeek: number;
                        recipeId: number;
                    };
                };
            };
            responses: {
                /** @description Swap done */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            mealPlan?: components["schemas"]["MealSlot"][];
                        };
                    };
                };
                400: components["responses"]["BadRequest"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meals/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update status of a meal slot */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        weekYear?: string;
                        dayOfWeek: number;
                        /** @enum {string} */
                        status: "planned" | "cooked" | "skipped" | "away";
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["BadRequest"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all recipes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipes?: components["schemas"]["Recipe"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single recipe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recipe */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            recipe?: components["schemas"]["Recipe"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Computed shopping list for the current week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Shopping list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ShoppingListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shopping/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add an extra item to the shopping list */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name: string;
                        category: string;
                        quantity?: number;
                    };
                };
            };
            responses: {
                /** @description Added */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chore schedule for the current week */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Chores */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            weekYear?: string;
                            chores?: components["schemas"]["Chore"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chores/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mark a chore as completed */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        weekYear?: string;
                        choreId: number;
                    };
                };
            };
            responses: {
                /** @description Marked done */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List calendar events in a date range */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            events?: components["schemas"]["CalendarEvent"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new calendar event */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CalendarEvent"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            event?: components["schemas"]["CalendarEvent"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a calendar event */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check LLM availability and current backend
         * @description Returns LLM (Ollama/llama.cpp) availability, model name, and STT
         *     backend status. Does not require LLM to be running — returns a
         *     disabled-state payload when backend is unreachable.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description LLM status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            available?: boolean;
                            /** @enum {string} */
                            backend?: "ollama" | "llamacpp";
                            model?: string;
                            models?: string[];
                            stt?: {
                                available?: boolean;
                                backend?: string;
                            };
                            kb?: {
                                totalInteractions?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a chat message to the local LLM (with tool-calling) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        message: string;
                        history?: {
                            /** @enum {string} */
                            role?: "user" | "assistant";
                            content?: string;
                        }[];
                        saveToKB?: boolean;
                    };
                };
            };
            responses: {
                /** @description LLM response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            response?: string;
                            toolCalls?: Record<string, never>[];
                        };
                    };
                };
                /** @description LLM not available */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/recipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a recipe from text (cached 7 days) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        query: string;
                    };
                };
            };
            responses: {
                /** @description Recipe JSON */
                200: {
                    headers: {
                        "X-LLM-Cache"?: "HIT" | "MISS";
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cache statistics (response cache + LLM cache) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            responseCache?: {
                                size?: number;
                                hits?: number;
                                misses?: number;
                            };
                            llmCache?: {
                                entries?: number;
                                totalHits?: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit log (SBOM-6) - read-only append-only log over destruktive ops
         * @description Returnerer de siste N audit-entries. Hver entry inneholder request-id,
         *     sha256 before/after-hashes, entity-type + id, og metadata. Eksponeres
         *     i produksjon for inspeksjon av hvem som gjorde hva, nar.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    /** @description Filtrer paa entity-type, f.eks. "recipe", "family_profile" */
                    entityType?: string;
                    entityId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries?: {
                                id?: number;
                                timestamp?: string;
                                requestId?: string;
                                actor?: string;
                                /** @enum {string} */
                                action?: "DELETE" | "PUT" | "PATCH" | "POST";
                                entityType?: string;
                                entityId?: string | null;
                                route?: string;
                                beforeHash?: string | null;
                                afterHash?: string | null;
                                metadata?: Record<string, never> | null;
                            }[];
                            count?: number;
                            note?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit log statistikk (SBOM-6) - aggregater */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Audit stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total?: number;
                            byAction?: {
                                action?: string;
                                c?: number;
                            }[];
                            byEntity?: {
                                entity_type?: string;
                                c?: number;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details */
        Problem: {
            /**
             * Format: uri
             * @example about:blank
             */
            type?: string;
            /** @example Bad Request */
            title?: string;
            /** @example 400 */
            status?: number;
            detail?: string;
            instance?: string;
            /** @description Field-level validation errors */
            errors?: {
                path?: string;
                message?: string;
            }[];
        };
        Health: {
            /** @example ok */
            status?: string;
            uptimeSec?: number;
            pid?: number;
            memMB?: number;
        };
        Ready: {
            ready?: boolean;
            /** @enum {string} */
            driver?: "better-sqlite3" | "sql.js" | "none";
            kbEntries?: number;
            fts5?: boolean;
        };
        MealSlot: {
            id?: number;
            /** @example 2026-W15 */
            weekYear?: string;
            dayOfWeek?: number;
            dayName?: string;
            /** @example middag */
            mealType?: string;
            recipeId?: number | null;
            /** @enum {string} */
            status?: "planned" | "cooked" | "skipped" | "away";
            recipe?: components["schemas"]["Recipe"];
        };
        MealsResponse: {
            weekYear?: string;
            meals?: components["schemas"]["MealSlot"][];
        };
        Recipe: {
            id?: number;
            name?: string;
            /** @enum {string} */
            category?: "rask" | "comfort" | "helg";
            prepTime?: string;
            servings?: number;
            ingredients?: components["schemas"]["RecipeIngredient"][];
        };
        RecipeIngredient: {
            id?: number;
            productKey?: string | null;
            name?: string;
            qty?: number;
            unit?: string;
            optional?: boolean;
        };
        ShoppingListResponse: {
            weekYear?: string;
            categories?: {
                name?: string;
                items?: {
                    key?: string;
                    name?: string;
                    qty?: number;
                    unit?: string;
                    /** @enum {string} */
                    source?: "recipe" | "consumable" | "extra";
                }[];
            }[];
        };
        Chore: {
            choreId?: number;
            task?: string;
            icon?: string;
            frequency?: string;
            scheduledDay?: number;
            postponedTo?: number | null;
            effectiveDay?: number;
            dayName?: string;
            /** @enum {string} */
            status?: "pending" | "done" | "postponed";
        };
        CalendarEvent: {
            readonly id?: number;
            title: string;
            /** Format: date */
            date: string;
            startTime?: string | null;
            endTime?: string | null;
            location?: string | null;
            allDay?: boolean;
            notes?: string | null;
        };
        TodayResponse: {
            dayName?: string;
            dayOfWeek?: number;
            weekYear?: string;
            meal?: components["schemas"]["MealSlot"];
            chores?: components["schemas"]["Chore"][];
            events?: components["schemas"]["CalendarEvent"][];
        };
        MetricsSnapshot: {
            uptimeSec?: number;
            totalRequests?: number;
            totalErrors?: number;
            errorRate?: number;
            routes?: {
                route?: string;
                count?: number;
                avgMs?: number;
                p50Ms?: number;
                p95Ms?: number;
                p99Ms?: number;
            }[];
        };
    };
    responses: {
        /** @description Validation or malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing or invalid bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource or route not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                "X-RateLimit-Limit"?: number;
                "X-RateLimit-Remaining"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
