// Tests for the useRecipePicker hook. We mock fetchRecipes and
// swapMeal and verify the state machine through plan/swap → fetch
// → select → close.

import { describe, expect, test, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';

const mocks = vi.hoisted(() => ({
  fetchRecipes: vi.fn(),
  swapMeal: vi.fn(),
}));

vi.mock('./mealsApi', async () => {
  const actual = await vi.importActual<typeof import('./mealsApi')>('./mealsApi');
  return {
    ...actual,
    fetchRecipes: mocks.fetchRecipes,
    swapMeal: mocks.swapMeal,
  };
});

import { useRecipePicker } from './useRecipePicker';

describe('useRecipePicker', () => {
  beforeEach(() => {
    mocks.fetchRecipes.mockReset();
    mocks.swapMeal.mockReset();
  });

  afterEach(() => {
    vi.clearAllMocks();
  });

  test('openForPlan opens dialog, sets mode=plan, fetches recipes', async () => {
    mocks.fetchRecipes.mockResolvedValue({
      recipes: [{ id: 1, name: 'Pizza', category: 'rask', prepTime: '15 min', servings: 2 }],
      filter: { ignoreDietTags: false, activeDietTags: [] },
    });
    const { result } = renderHook(() => useRecipePicker('2026-W18'));

    await act(async () => {
      await result.current.openForPlan(0);
    });

    expect(result.current.state.open).toBe(true);
    expect(result.current.state.mode).toBe('plan');
    expect(result.current.state.dayOfWeek).toBe(0);
    expect(result.current.state.recipes).toHaveLength(1);
    expect(result.current.state.currentRecipeId).toBeNull();
  });

  test('openForSwap stores currentRecipeId for the dialog flag', async () => {
    mocks.fetchRecipes.mockResolvedValue({
      recipes: [],
      filter: { ignoreDietTags: false, activeDietTags: [] },
    });
    const { result } = renderHook(() => useRecipePicker('2026-W18'));

    await act(async () => {
      await result.current.openForSwap(2, 7);
    });

    expect(result.current.state.mode).toBe('swap');
    expect(result.current.state.currentRecipeId).toBe(7);
  });

  test('open() surfaces error when fetchRecipes fails', async () => {
    mocks.fetchRecipes.mockRejectedValue(new Error('500'));
    const { result } = renderHook(() => useRecipePicker('2026-W18'));

    await act(async () => {
      await result.current.openForPlan(0);
    });

    expect(result.current.state.error).toBeTruthy();
    expect(result.current.state.loading).toBe(false);
  });

  test('select() calls swapMeal with weekYear/dayOfWeek/recipeId, then closes', async () => {
    mocks.fetchRecipes.mockResolvedValue({
      recipes: [{ id: 1, name: 'Pizza', category: 'rask', prepTime: null, servings: null }],
      filter: { ignoreDietTags: false, activeDietTags: [] },
    });
    mocks.swapMeal.mockResolvedValue({ ok: true, mealPlan: [], autogeneratedShoppingList: null });
    const onAfterSwap = vi.fn();
    const { result } = renderHook(() => useRecipePicker('2026-W18', onAfterSwap));

    await act(async () => {
      await result.current.openForPlan(3);
    });
    await act(async () => {
      await result.current.select(1);
    });

    expect(mocks.swapMeal).toHaveBeenCalledWith('2026-W18', 3, 1);
    expect(result.current.state.open).toBe(false);
    expect(onAfterSwap).toHaveBeenCalled();
  });

  test('select() preserves dialog open with applyError when swap fails', async () => {
    mocks.fetchRecipes.mockResolvedValue({
      recipes: [{ id: 1, name: 'Pizza', category: 'rask', prepTime: null, servings: null }],
      filter: { ignoreDietTags: false, activeDietTags: [] },
    });
    mocks.swapMeal.mockRejectedValue(new Error('500'));
    const { result } = renderHook(() => useRecipePicker('2026-W18'));

    await act(async () => {
      await result.current.openForPlan(3);
    });
    await act(async () => {
      await result.current.select(1);
    });

    expect(result.current.state.applyError).toBeTruthy();
    expect(result.current.state.open).toBe(true);
  });

  test('select() is a no-op when weekYear is null', async () => {
    mocks.fetchRecipes.mockResolvedValue({
      recipes: [{ id: 1, name: 'Pizza', category: 'rask', prepTime: null, servings: null }],
      filter: { ignoreDietTags: false, activeDietTags: [] },
    });
    const { result } = renderHook(() => useRecipePicker(null));

    await act(async () => {
      await result.current.openForPlan(3);
    });
    await act(async () => {
      await result.current.select(1);
    });

    expect(mocks.swapMeal).not.toHaveBeenCalled();
  });

  test('close() resets to idle without calling APIs', () => {
    const { result } = renderHook(() => useRecipePicker('2026-W18'));
    act(() => {
      result.current.close();
    });
    expect(result.current.state.open).toBe(false);
    expect(mocks.fetchRecipes).not.toHaveBeenCalled();
    expect(mocks.swapMeal).not.toHaveBeenCalled();
  });
});
