// Seed-data for Familieassistenten
// Alle produkter, oppskrifter, husarbeid og consumables

const products = {
  // === KJØTT & FISK ===
  "kyllingfilet": { productName: "Kyllingfilet", category: "Kjøtt & fisk", packSize: 500, unit: "g", estPrice: 89, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "laksefilet": { productName: "Laksefilet", category: "Kjøtt & fisk", packSize: 400, unit: "g", estPrice: 159, shelfDays: 2, store: "Kiwi Vågsbygd", dairyRule: null },
  "scampi": { productName: "Scampi fryst", category: "Kjøtt & fisk", packSize: 300, unit: "g", estPrice: 99, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "biffstrimler": { productName: "Biffstrimler", category: "Kjøtt & fisk", packSize: 400, unit: "g", estPrice: 129, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "kjøttdeig": { productName: "Kjøttdeig", category: "Kjøtt & fisk", packSize: 500, unit: "g", estPrice: 99, shelfDays: 2, store: "Kiwi Vågsbygd", dairyRule: null },
  "nakkekoteletter": { productName: "Nakkekoteletter", category: "Kjøtt & fisk", packSize: 600, unit: "g", estPrice: 149, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "svinekjøtt": { productName: "Svinekjøtt pulled", category: "Kjøtt & fisk", packSize: 800, unit: "g", estPrice: 129, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "biff": { productName: "Biffstykker", category: "Kjøtt & fisk", packSize: 400, unit: "g", estPrice: 169, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "hel kylling": { productName: "Hel kylling", category: "Kjøtt & fisk", packSize: 1800, unit: "g", estPrice: 149, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "lam": { productName: "Lam kjøtt stew", category: "Kjøtt & fisk", packSize: 600, unit: "g", estPrice: 189, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "oksekjøtt": { productName: "Oksekjøtt", category: "Kjøtt & fisk", packSize: 500, unit: "g", estPrice: 199, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "ribs": { productName: "Ribs svin", category: "Kjøtt & fisk", packSize: 1200, unit: "g", estPrice: 179, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "kjøttpølser": { productName: "Kjøttpølser", category: "Kjøtt & fisk", packSize: 400, unit: "g", estPrice: 69, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "bacon": { productName: "Bacon", category: "Kjøtt & fisk", packSize: 200, unit: "g", estPrice: 59, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "røkt laks": { productName: "Røkt laks", category: "Kjøtt & fisk", packSize: 150, unit: "g", estPrice: 79, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "pepperoni": { productName: "Pepperoni", category: "Kjøtt & fisk", packSize: 100, unit: "g", estPrice: 49, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },

  // === MEIERI ===
  "melk": { productName: "Røros helmelk 1L", category: "Meieri", packSize: 1000, unit: "ml", estPrice: 25.90, shelfDays: 10, store: "Kiwi Vågsbygd", dairyRule: "røros_only" },
  "lettmelk": { productName: "Røros lettmelk 1L", category: "Meieri", packSize: 1000, unit: "ml", estPrice: 25.90, shelfDays: 10, store: "Kiwi Vågsbygd", dairyRule: "røros_only" },
  "fløte": { productName: "Røros fløte 3dl", category: "Meieri", packSize: 300, unit: "ml", estPrice: 29, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: "røros_preferred" },
  "rømme": { productName: "Røros rømme 3dl", category: "Meieri", packSize: 300, unit: "ml", estPrice: 25, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: "røros_preferred" },
  "smør": { productName: "Smør", category: "Meieri", packSize: 250, unit: "g", estPrice: 79, shelfDays: 30, store: "Kiwi Vågsbygd", dairyRule: null },
  "egg": { productName: "Egg (10stk)", category: "Meieri", packSize: 10, unit: "stk", estPrice: 39, shelfDays: 21, store: "Kiwi Vågsbygd", dairyRule: null },
  "mozzarella": { productName: "Mozzarella", category: "Meieri", packSize: 500, unit: "g", estPrice: 129, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },
  "cheddar": { productName: "Cheddar", category: "Meieri", packSize: 400, unit: "g", estPrice: 119, shelfDays: 21, store: "Kiwi Vågsbygd", dairyRule: null },
  "parmesan": { productName: "Parmesan", category: "Meieri", packSize: 200, unit: "g", estPrice: 99, shelfDays: 21, store: "Kiwi Vågsbygd", dairyRule: null },
  "ricotta": { productName: "Ricotta", category: "Meieri", packSize: 500, unit: "g", estPrice: 99, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },
  "ost": { productName: "Ost blanding", category: "Meieri", packSize: 500, unit: "g", estPrice: 99, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },

  // === FRUKT & GRØNT ===
  "paprika": { productName: "Paprika rød", category: "Frukt & grønt", packSize: 3, unit: "stk", estPrice: 29, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },
  "sukkererter": { productName: "Sukkererter", category: "Frukt & grønt", packSize: 300, unit: "g", estPrice: 19, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "brokkolini": { productName: "Brokkolini", category: "Frukt & grønt", packSize: 300, unit: "g", estPrice: 35, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "poteter": { productName: "Poteter", category: "Frukt & grønt", packSize: 2000, unit: "g", estPrice: 29, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "søtpotet": { productName: "Søtpotet", category: "Frukt & grønt", packSize: 1000, unit: "g", estPrice: 35, shelfDays: 10, store: "Kiwi Vågsbygd", dairyRule: null },
  "vårløk": { productName: "Vårløk", category: "Frukt & grønt", packSize: 200, unit: "g", estPrice: 15, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "løk": { productName: "Løk", category: "Frukt & grønt", packSize: 1500, unit: "g", estPrice: 15, shelfDays: 21, store: "Kiwi Vågsbygd", dairyRule: null },
  "hvitløk": { productName: "Hvitløk", category: "Frukt & grønt", packSize: 500, unit: "g", estPrice: 25, shelfDays: 21, store: "Kiwi Vågsbygd", dairyRule: null },
  "ingefær": { productName: "Ingefær", category: "Frukt & grønt", packSize: 200, unit: "g", estPrice: 19, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "sitron": { productName: "Sitron", category: "Frukt & grønt", packSize: 4, unit: "stk", estPrice: 15, shelfDays: 10, store: "Kiwi Vågsbygd", dairyRule: null },
  "lime": { productName: "Lime", category: "Frukt & grønt", packSize: 3, unit: "stk", estPrice: 15, shelfDays: 10, store: "Kiwi Vågsbygd", dairyRule: null },
  "isbergsalat": { productName: "Isbergsalat", category: "Frukt & grønt", packSize: 300, unit: "g", estPrice: 25, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "tomat": { productName: "Tomat", category: "Frukt & grønt", packSize: 1000, unit: "g", estPrice: 35, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "gulrot": { productName: "Gulrot", category: "Frukt & grønt", packSize: 1000, unit: "g", estPrice: 12, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "sellerirot": { productName: "Sellerirot", category: "Frukt & grønt", packSize: 500, unit: "g", estPrice: 15, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "basilikum": { productName: "Basilikum fersk", category: "Frukt & grønt", packSize: 25, unit: "g", estPrice: 12, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "persille": { productName: "Persille fersk", category: "Frukt & grønt", packSize: 30, unit: "g", estPrice: 12, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "dill": { productName: "Dill fersk", category: "Frukt & grønt", packSize: 30, unit: "g", estPrice: 12, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "timian": { productName: "Timian fersk", category: "Frukt & grønt", packSize: 20, unit: "g", estPrice: 12, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },
  "estragon": { productName: "Estragon fersk", category: "Frukt & grønt", packSize: 20, unit: "g", estPrice: 12, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "spinat": { productName: "Spinat fersk", category: "Frukt & grønt", packSize: 300, unit: "g", estPrice: 29, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "kål": { productName: "Kål", category: "Frukt & grønt", packSize: 1000, unit: "g", estPrice: 12, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "mais": { productName: "Mais fryst", category: "Frukt & grønt", packSize: 400, unit: "g", estPrice: 15, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "agurk": { productName: "Agurk", category: "Frukt & grønt", packSize: 3, unit: "stk", estPrice: 15, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "mango": { productName: "Mango", category: "Frukt & grønt", packSize: 2, unit: "stk", estPrice: 25, shelfDays: 5, store: "Kiwi Vågsbygd", dairyRule: null },
  "avokado": { productName: "Avokado", category: "Frukt & grønt", packSize: 2, unit: "stk", estPrice: 35, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "chili": { productName: "Chili rød", category: "Frukt & grønt", packSize: 3, unit: "stk", estPrice: 15, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },

  // === TØRRVARER & ANNET ===
  "jasminris": { productName: "Jasminris", category: "Tørrvarer & annet", packSize: 1000, unit: "g", estPrice: 35, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "ris": { productName: "Basmati-ris", category: "Tørrvarer & annet", packSize: 1000, unit: "g", estPrice: 35, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "spaghetti": { productName: "Spaghetti", category: "Tørrvarer & annet", packSize: 500, unit: "g", estPrice: 15, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "pasta": { productName: "Pasta blanda", category: "Tørrvarer & annet", packSize: 500, unit: "g", estPrice: 15, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "nudler": { productName: "Nudler asiatisk", category: "Tørrvarer & annet", packSize: 400, unit: "g", estPrice: 25, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "lasagneplater": { productName: "Lasagneplater", category: "Tørrvarer & annet", packSize: 500, unit: "g", estPrice: 19, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "red curry paste": { productName: "Red curry paste", category: "Tørrvarer & annet", packSize: 400, unit: "g", estPrice: 39, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "kokosmelk": { productName: "Kokosmelk boks", category: "Tørrvarer & annet", packSize: 400, unit: "ml", estPrice: 22, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "soyasaus": { productName: "Soyasaus", category: "Tørrvarer & annet", packSize: 300, unit: "ml", estPrice: 35, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "san marzano-tomater": { productName: "San Marzano-tomater", category: "Tørrvarer & annet", packSize: 400, unit: "g", estPrice: 19, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "bbq-saus": { productName: "BBQ-saus", category: "Tørrvarer & annet", packSize: 400, unit: "ml", estPrice: 45, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "sriracha": { productName: "Sriracha-saus", category: "Tørrvarer & annet", packSize: 200, unit: "ml", estPrice: 35, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "majones": { productName: "Majones", category: "Tørrvarer & annet", packSize: 400, unit: "g", estPrice: 25, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "aioli": { productName: "Aioli", category: "Tørrvarer & annet", packSize: 300, unit: "g", estPrice: 35, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "pesto": { productName: "Pesto grønn", category: "Tørrvarer & annet", packSize: 190, unit: "g", estPrice: 39, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "olivenolje": { productName: "Olivenolje", category: "Tørrvarer & annet", packSize: 500, unit: "ml", estPrice: 89, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "honning": { productName: "Honning", category: "Tørrvarer & annet", packSize: 400, unit: "g", estPrice: 59, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "brunt sukker": { productName: "Brunt sukker", category: "Tørrvarer & annet", packSize: 1000, unit: "g", estPrice: 29, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "mel": { productName: "Hvetemel", category: "Tørrvarer & annet", packSize: 1000, unit: "g", estPrice: 19, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "gjær": { productName: "Gjær", category: "Tørrvarer & annet", packSize: 50, unit: "g", estPrice: 35, shelfDays: 14, store: "Kiwi Vågsbygd", dairyRule: null },
  "cashewnøtter": { productName: "Cashewnøtter ristede", category: "Tørrvarer & annet", packSize: 200, unit: "g", estPrice: 79, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "nachos": { productName: "Nachos chips", category: "Tørrvarer & annet", packSize: 300, unit: "g", estPrice: 29, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },
  "rødvin": { productName: "Rødvin", category: "Tørrvarer & annet", packSize: 750, unit: "ml", estPrice: 99, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
  "sylteagurk": { productName: "Sylteagurk", category: "Tørrvarer & annet", packSize: 370, unit: "g", estPrice: 15, shelfDays: 180, store: "Kiwi Vågsbygd", dairyRule: null },

  // === BRØD & BAKST ===
  "briochebrød": { productName: "Briochebrød", category: "Brød & bakst", packSize: 4, unit: "stk", estPrice: 39, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "pizzadeig": { productName: "Pizzadeig fersk", category: "Brød & bakst", packSize: 500, unit: "g", estPrice: 19, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "brød": { productName: "Brød", category: "Brød & bakst", packSize: 500, unit: "g", estPrice: 29, shelfDays: 3, store: "Kiwi Vågsbygd", dairyRule: null },
  "pitabrød": { productName: "Pitabrød", category: "Brød & bakst", packSize: 300, unit: "g", estPrice: 19, shelfDays: 4, store: "Kiwi Vågsbygd", dairyRule: null },
  "tortilla": { productName: "Tortilla hvete", category: "Brød & bakst", packSize: 300, unit: "g", estPrice: 19, shelfDays: 7, store: "Kiwi Vågsbygd", dairyRule: null },
  "tacoskjell": { productName: "Tacoskjell", category: "Brød & bakst", packSize: 200, unit: "g", estPrice: 19, shelfDays: 365, store: "Kiwi Vågsbygd", dairyRule: null },
};

const recipes = [
  {
    id: 1,
    name: "Kylling red curry med jasminris",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/gryte/8421/varmende-red-curry-paa-30-minutter",
    servings: 2,
    equipment: ["stekepanne", "kjele"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 400, unit: "g" },
      { productKey: "red curry paste", name: "Red curry paste", qty: 2, unit: "ss" },
      { productKey: "kokosmelk", name: "Kokosmelk", qty: 400, unit: "ml" },
      { productKey: "paprika", name: "Paprika", qty: 1, unit: "stk" },
      { productKey: "sukkererter", name: "Sukkererter", qty: 200, unit: "g" },
      { productKey: "jasminris", name: "Jasminris", qty: 300, unit: "g" },
      { productKey: "lime", name: "Lime", qty: 0.5, unit: "stk" },
    ],
  },
  {
    id: 2,
    name: "Laks i airfryer med potetbåter og brokkolini",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/rask/laks-i-airfryer/",
    servings: 2,
    equipment: ["airfryer"],
    ingredients: [
      { productKey: "laksefilet", name: "Laksefilet", qty: 400, unit: "g" },
      { productKey: "poteter", name: "Poteter", qty: 500, unit: "g" },
      { productKey: "brokkolini", name: "Brokkolini", qty: 300, unit: "g" },
      { productKey: "sitron", name: "Sitron", qty: 0.5, unit: "stk" },
      { productKey: "olivenolje", name: "Olivenolje", qty: 2, unit: "ss" },
    ],
  },
  {
    id: 3,
    name: "Pasta med scampi, hvitløk og chili",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne", "kjele"],
    ingredients: [
      { productKey: "scampi", name: "Scampi", qty: 300, unit: "g" },
      { productKey: "spaghetti", name: "Spaghetti", qty: 400, unit: "g" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 3, unit: "fedd" },
      { productKey: "chili", name: "Chili", qty: 1, unit: "stk" },
      { productKey: "persille", name: "Persille", qty: 15, unit: "g" },
      { productKey: "sitron", name: "Sitron", qty: 0.5, unit: "stk" },
      { productKey: "smør", name: "Smør", qty: 50, unit: "g" },
    ],
  },
  {
    id: 4,
    name: "Mongolian beef med ris og wokede grønnsaker",
    category: "rask",
    prepTime: "30 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["wok", "kjele"],
    ingredients: [
      { productKey: "biffstrimler", name: "Biffstrimler", qty: 400, unit: "g" },
      { productKey: "vårløk", name: "Vårløk", qty: 150, unit: "g" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 3, unit: "ss" },
      { productKey: "brunt sukker", name: "Brunt sukker", qty: 2, unit: "ss" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 2, unit: "fedd" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
    ],
  },
  {
    id: 5,
    name: "Smashburger i brioche med løkringer og coleslaw",
    category: "comfort",
    prepTime: "45 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/kos/smash-burger/",
    servings: 2,
    equipment: ["stekepanne", "Foreman grill"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig", qty: 400, unit: "g" },
      { productKey: "briochebrød", name: "Briochebrød", qty: 2, unit: "stk" },
      { productKey: "cheddar", name: "Cheddar", qty: 100, unit: "g" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "sylteagurk", name: "Sylteagurk", qty: 50, unit: "g" },
      { productKey: "isbergsalat", name: "Isbergsalat", qty: 150, unit: "g" },
      { productKey: "tomat", name: "Tomat", qty: 1, unit: "stk" },
    ],
  },
  {
    id: 6,
    name: "Hjemmelaget pizza på pizzastein",
    category: "helg",
    prepTime: "1,5 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekeovn", "pizzastein"],
    ingredients: [
      { productKey: "pizzadeig", name: "Pizzadeig", qty: 500, unit: "g" },
      { productKey: "san marzano-tomater", name: "San Marzano-tomater", qty: 400, unit: "g" },
      { productKey: "mozzarella", name: "Mozzarella", qty: 250, unit: "g" },
      { productKey: "pepperoni", name: "Pepperoni", qty: 80, unit: "g" },
      { productKey: "basilikum", name: "Basilikum", qty: 10, unit: "g" },
      { productKey: "olivenolje", name: "Olivenolje", qty: 3, unit: "ss" },
    ],
  },
  {
    id: 7,
    name: "Langtidsstekt nakkekoteletter med rotgrønnsaker",
    category: "helg",
    prepTime: "3 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekeovn", "støpejernsgryte"],
    ingredients: [
      { productKey: "nakkekoteletter", name: "Nakkekoteletter", qty: 600, unit: "g" },
      { productKey: "gulrot", name: "Gulrot", qty: 300, unit: "g" },
      { productKey: "sellerirot", name: "Sellerirot", qty: 200, unit: "g" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "timian", name: "Timian", qty: 5, unit: "g" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 2, unit: "fedd" },
    ],
  },
  // === ALTERNATIVER ===
  {
    id: 8,
    name: "Wok med kylling, cashewnøtter og grønnsaker",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["wok"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 400, unit: "g" },
      { productKey: "cashewnøtter", name: "Cashewnøtter", qty: 100, unit: "g" },
      { productKey: "paprika", name: "Paprika", qty: 1, unit: "stk" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 2, unit: "ss" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
    ],
  },
  {
    id: 9,
    name: "Enkel kyllingsuppe med nudler",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["kjele"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 300, unit: "g" },
      { productKey: "nudler", name: "Nudler", qty: 150, unit: "g" },
      { productKey: "gulrot", name: "Gulrot", qty: 150, unit: "g" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
    ],
  },
  {
    id: 10,
    name: "Stekt ris med egg og grønnsaker",
    category: "rask",
    prepTime: "15 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["wok"],
    ingredients: [
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
      { productKey: "egg", name: "Egg", qty: 2, unit: "stk" },
      { productKey: "vårløk", name: "Vårløk", qty: 100, unit: "g" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 1, unit: "ss" },
    ],
  },
  {
    id: 11,
    name: "Kylling i airfryer med søtpotet",
    category: "rask",
    prepTime: "25 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/rask/kyllingfilet-i-airfryer/",
    servings: 2,
    equipment: ["airfryer"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 400, unit: "g" },
      { productKey: "søtpotet", name: "Søtpotet", qty: 500, unit: "g" },
      { productKey: "olivenolje", name: "Olivenolje", qty: 2, unit: "ss" },
    ],
  },
  {
    id: 12,
    name: "Dumplings i bambusdamper med dippsaus",
    category: "rask",
    prepTime: "30 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["bambusdamper"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig", qty: 250, unit: "g" },
      { productKey: "vårløk", name: "Vårløk", qty: 100, unit: "g" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 2, unit: "ss" },
    ],
  },
  {
    id: 13,
    name: "Lakseburgere med avokado og srirachamayo",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne"],
    ingredients: [
      { productKey: "laksefilet", name: "Laksefilet", qty: 400, unit: "g" },
      { productKey: "avokado", name: "Avokado", qty: 1, unit: "stk" },
      { productKey: "sriracha", name: "Sriracha", qty: 1, unit: "ss" },
      { productKey: "majones", name: "Majones", qty: 100, unit: "g" },
    ],
  },
  {
    id: 14,
    name: "Bakt laks med honning og soya i airfryer",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/rask/laks-i-airfryer/",
    servings: 2,
    equipment: ["airfryer"],
    ingredients: [
      { productKey: "laksefilet", name: "Laksefilet", qty: 400, unit: "g" },
      { productKey: "honning", name: "Honning", qty: 2, unit: "ss" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 2, unit: "ss" },
    ],
  },
  {
    id: 15,
    name: "Pasta med røkt laks og fløtesaus",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["kjele", "stekepanne"],
    ingredients: [
      { productKey: "røkt laks", name: "Røkt laks", qty: 150, unit: "g" },
      { productKey: "pasta", name: "Pasta", qty: 400, unit: "g" },
      { productKey: "fløte", name: "Fløte", qty: 150, unit: "ml" },
      { productKey: "dill", name: "Dill", qty: 10, unit: "g" },
    ],
  },
  {
    id: 16,
    name: "Fish tacos med laks og mangosalsa",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne"],
    ingredients: [
      { productKey: "laksefilet", name: "Laksefilet", qty: 300, unit: "g" },
      { productKey: "tortilla", name: "Tortilla", qty: 150, unit: "g" },
      { productKey: "mango", name: "Mango", qty: 1, unit: "stk" },
      { productKey: "lime", name: "Lime", qty: 1, unit: "stk" },
    ],
  },
  // === FLERE OPPSKRIFTER ===
  {
    id: 17,
    name: "Pulled pork i airfryer med coleslaw og brioche",
    category: "comfort",
    prepTime: "1 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["airfryer"],
    ingredients: [
      { productKey: "svinekjøtt", name: "Svinekjøtt pulled", qty: 600, unit: "g" },
      { productKey: "bbq-saus", name: "BBQ-saus", qty: 100, unit: "ml" },
      { productKey: "briochebrød", name: "Briochebrød", qty: 2, unit: "stk" },
      { productKey: "kål", name: "Kål (coleslaw)", qty: 200, unit: "g" },
      { productKey: "majones", name: "Majones", qty: 50, unit: "g" },
    ],
  },
  {
    id: 18,
    name: "Taco fredag med kjøttdeig og alle toppings",
    category: "comfort",
    prepTime: "30 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/kos/taco/",
    servings: 2,
    equipment: ["stekepanne"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig", qty: 400, unit: "g" },
      { productKey: "tacoskjell", name: "Tacoskjell", qty: 200, unit: "g" },
      { productKey: "rømme", name: "Rømme", qty: 150, unit: "ml" },
      { productKey: "tomat", name: "Tomat", qty: 2, unit: "stk" },
      { productKey: "isbergsalat", name: "Isbergsalat", qty: 150, unit: "g" },
      { productKey: "paprika", name: "Paprika", qty: 1, unit: "stk" },
      { productKey: "ost", name: "Ost revet", qty: 100, unit: "g" },
    ],
  },
  {
    id: 19,
    name: "Kylling tikka masala med naanbrød",
    category: "rask",
    prepTime: "30 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne", "kjele"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 400, unit: "g" },
      { productKey: "san marzano-tomater", name: "Tomater hermetisk", qty: 400, unit: "g" },
      { productKey: "fløte", name: "Fløte", qty: 100, unit: "ml" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 3, unit: "fedd" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
    ],
  },
  {
    id: 20,
    name: "Lasagne med kjøttsaus og ostesaus",
    category: "helg",
    prepTime: "1,5 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/kos/lasagne/",
    servings: 2,
    equipment: ["stekeovn", "kjele", "stekepanne"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig", qty: 400, unit: "g" },
      { productKey: "lasagneplater", name: "Lasagneplater", qty: 250, unit: "g" },
      { productKey: "san marzano-tomater", name: "Tomater hermetisk", qty: 400, unit: "g" },
      { productKey: "fløte", name: "Fløte", qty: 200, unit: "ml" },
      { productKey: "mozzarella", name: "Mozzarella", qty: 200, unit: "g" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 2, unit: "fedd" },
    ],
  },
  {
    id: 21,
    name: "Bibimbap — koreansk risrett med biff og grønnsaker",
    category: "rask",
    prepTime: "30 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["wok", "riskoker"],
    ingredients: [
      { productKey: "biffstrimler", name: "Biffstrimler", qty: 300, unit: "g" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
      { productKey: "egg", name: "Egg", qty: 2, unit: "stk" },
      { productKey: "gulrot", name: "Gulrot", qty: 150, unit: "g" },
      { productKey: "spinat", name: "Spinat", qty: 100, unit: "g" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 2, unit: "ss" },
      { productKey: "sriracha", name: "Sriracha", qty: 1, unit: "ss" },
    ],
  },
  {
    id: 22,
    name: "Hjemmelaget kebab med pitabrød og tzatziki",
    category: "comfort",
    prepTime: "40 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekeovn", "Foreman grill"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig (lam/okse)", qty: 400, unit: "g" },
      { productKey: "pitabrød", name: "Pitabrød", qty: 300, unit: "g" },
      { productKey: "tomat", name: "Tomat", qty: 2, unit: "stk" },
      { productKey: "isbergsalat", name: "Isbergsalat", qty: 100, unit: "g" },
      { productKey: "rømme", name: "Rømme (tzatziki)", qty: 100, unit: "ml" },
      { productKey: "agurk", name: "Agurk", qty: 0.5, unit: "stk" },
      { productKey: "løk", name: "Rødløk", qty: 0.5, unit: "stk" },
    ],
  },
  {
    id: 23,
    name: "Grillet biff med bearnaisesaus og ovnsbakte poteter",
    category: "helg",
    prepTime: "45 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["gassgrill", "stekeovn"],
    ingredients: [
      { productKey: "biff", name: "Biffstykker", qty: 400, unit: "g" },
      { productKey: "poteter", name: "Poteter", qty: 500, unit: "g" },
      { productKey: "smør", name: "Smør", qty: 80, unit: "g" },
      { productKey: "egg", name: "Egg (plomme)", qty: 2, unit: "stk" },
      { productKey: "estragon", name: "Estragon", qty: 10, unit: "g" },
      { productKey: "sitron", name: "Sitron", qty: 0.5, unit: "stk" },
    ],
  },
  {
    id: 24,
    name: "Thai-suppe med scampi og kokosmelk",
    category: "rask",
    prepTime: "20 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["kjele"],
    ingredients: [
      { productKey: "scampi", name: "Scampi", qty: 300, unit: "g" },
      { productKey: "kokosmelk", name: "Kokosmelk", qty: 400, unit: "ml" },
      { productKey: "red curry paste", name: "Red curry paste", qty: 1, unit: "ss" },
      { productKey: "lime", name: "Lime", qty: 1, unit: "stk" },
      { productKey: "vårløk", name: "Vårløk", qty: 100, unit: "g" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
    ],
  },
  {
    id: 25,
    name: "Nachos supreme med kjøttdeig og guacamole",
    category: "comfort",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne", "stekeovn"],
    ingredients: [
      { productKey: "kjøttdeig", name: "Kjøttdeig", qty: 300, unit: "g" },
      { productKey: "nachos", name: "Nachos", qty: 300, unit: "g" },
      { productKey: "avokado", name: "Avokado", qty: 2, unit: "stk" },
      { productKey: "rømme", name: "Rømme", qty: 100, unit: "ml" },
      { productKey: "cheddar", name: "Cheddar", qty: 150, unit: "g" },
      { productKey: "tomat", name: "Tomat", qty: 1, unit: "stk" },
      { productKey: "lime", name: "Lime", qty: 0.5, unit: "stk" },
    ],
  },
  {
    id: 26,
    name: "Pasta carbonara med bacon og parmesan",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/rask/pasta-carbonara/",
    servings: 2,
    equipment: ["kjele", "stekepanne"],
    ingredients: [
      { productKey: "spaghetti", name: "Spaghetti", qty: 400, unit: "g" },
      { productKey: "bacon", name: "Bacon", qty: 200, unit: "g" },
      { productKey: "egg", name: "Egg", qty: 3, unit: "stk" },
      { productKey: "parmesan", name: "Parmesan", qty: 80, unit: "g" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 2, unit: "fedd" },
    ],
  },
  {
    id: 27,
    name: "Helstekt kylling med ris og mangosalat",
    category: "helg",
    prepTime: "1,5 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekeovn"],
    ingredients: [
      { productKey: "hel kylling", name: "Hel kylling", qty: 1800, unit: "g" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
      { productKey: "mango", name: "Mango", qty: 1, unit: "stk" },
      { productKey: "lime", name: "Lime", qty: 1, unit: "stk" },
      { productKey: "olivenolje", name: "Olivenolje", qty: 3, unit: "ss" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 4, unit: "fedd" },
    ],
  },
  {
    id: 28,
    name: "Pad thai med scampi",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["wok"],
    ingredients: [
      { productKey: "scampi", name: "Scampi", qty: 250, unit: "g" },
      { productKey: "nudler", name: "Nudler", qty: 200, unit: "g" },
      { productKey: "egg", name: "Egg", qty: 2, unit: "stk" },
      { productKey: "vårløk", name: "Vårløk", qty: 100, unit: "g" },
      { productKey: "cashewnøtter", name: "Cashewnøtter", qty: 50, unit: "g" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 2, unit: "ss" },
      { productKey: "lime", name: "Lime", qty: 1, unit: "stk" },
    ],
  },
  {
    id: 29,
    name: "BBQ ribs med mais og potetsalat",
    category: "helg",
    prepTime: "3 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["stekeovn", "gassgrill"],
    ingredients: [
      { productKey: "ribs", name: "Ribs svin", qty: 1200, unit: "g" },
      { productKey: "bbq-saus", name: "BBQ-saus", qty: 150, unit: "ml" },
      { productKey: "mais", name: "Mais", qty: 400, unit: "g" },
      { productKey: "poteter", name: "Poteter", qty: 500, unit: "g" },
      { productKey: "majones", name: "Majones", qty: 50, unit: "g" },
    ],
  },
  {
    id: 30,
    name: "Lamgryte med rotgrønnsaker og timian",
    category: "helg",
    prepTime: "2,5 t",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["støpejernsgryte", "stekeovn"],
    ingredients: [
      { productKey: "lam", name: "Lam stew", qty: 600, unit: "g" },
      { productKey: "gulrot", name: "Gulrot", qty: 200, unit: "g" },
      { productKey: "poteter", name: "Poteter", qty: 400, unit: "g" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "timian", name: "Timian", qty: 5, unit: "g" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 3, unit: "fedd" },
      { productKey: "rødvin", name: "Rødvin", qty: 200, unit: "ml" },
    ],
  },
  {
    id: 31,
    name: "Pesto-pasta med kylling og soltørkede tomater",
    category: "rask",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["kjele", "stekepanne"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 300, unit: "g" },
      { productKey: "pasta", name: "Pasta", qty: 400, unit: "g" },
      { productKey: "pesto", name: "Pesto", qty: 100, unit: "g" },
      { productKey: "parmesan", name: "Parmesan", qty: 50, unit: "g" },
      { productKey: "spinat", name: "Spinat", qty: 100, unit: "g" },
    ],
  },
  {
    id: 32,
    name: "Oksegryte med øl og rotgrønnsaker",
    category: "helg",
    prepTime: "3 t",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["støpejernsgryte", "stekeovn"],
    ingredients: [
      { productKey: "oksekjøtt", name: "Oksekjøtt", qty: 500, unit: "g" },
      { productKey: "gulrot", name: "Gulrot", qty: 200, unit: "g" },
      { productKey: "sellerirot", name: "Sellerirot", qty: 150, unit: "g" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "poteter", name: "Poteter", qty: 400, unit: "g" },
      { productKey: "timian", name: "Timian", qty: 5, unit: "g" },
    ],
  },
  {
    id: 33,
    name: "Teriyaki-laks med ris og edamame",
    category: "rask",
    prepTime: "25 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne", "riskoker"],
    ingredients: [
      { productKey: "laksefilet", name: "Laksefilet", qty: 400, unit: "g" },
      { productKey: "soyasaus", name: "Soyasaus", qty: 3, unit: "ss" },
      { productKey: "honning", name: "Honning", qty: 1, unit: "ss" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
      { productKey: "vårløk", name: "Vårløk", qty: 50, unit: "g" },
    ],
  },
  {
    id: 34,
    name: "Kjøttpølser med potetmos og løksaus",
    category: "rask",
    prepTime: "25 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/",
    servings: 2,
    equipment: ["kjele", "stekepanne"],
    ingredients: [
      { productKey: "kjøttpølser", name: "Kjøttpølser", qty: 400, unit: "g" },
      { productKey: "poteter", name: "Poteter (mos)", qty: 600, unit: "g" },
      { productKey: "smør", name: "Smør", qty: 30, unit: "g" },
      { productKey: "melk", name: "Melk", qty: 100, unit: "ml" },
      { productKey: "løk", name: "Løk", qty: 1, unit: "stk" },
      { productKey: "fløte", name: "Fløte (saus)", qty: 100, unit: "ml" },
    ],
  },
  {
    id: 35,
    name: "Butter chicken med naanbrød",
    category: "rask",
    prepTime: "30 min",
    source: "godt.no",
    url: "https://www.godt.no/oppskrifter/",
    servings: 2,
    equipment: ["stekepanne", "kjele"],
    ingredients: [
      { productKey: "kyllingfilet", name: "Kyllingfilet", qty: 400, unit: "g" },
      { productKey: "san marzano-tomater", name: "Tomater hermetisk", qty: 400, unit: "g" },
      { productKey: "fløte", name: "Fløte", qty: 150, unit: "ml" },
      { productKey: "smør", name: "Smør", qty: 50, unit: "g" },
      { productKey: "hvitløk", name: "Hvitløk", qty: 3, unit: "fedd" },
      { productKey: "ingefær", name: "Ingefær", qty: 1, unit: "ts" },
      { productKey: "ris", name: "Ris", qty: 300, unit: "g" },
    ],
  },
  {
    id: 36,
    name: "Vafler med rømme og syltetøy",
    category: "helg",
    prepTime: "20 min",
    source: "matprat.no",
    url: "https://www.matprat.no/oppskrifter/bakst/vafler/",
    servings: 2,
    equipment: ["vaffeljern"],
    ingredients: [
      { productKey: "mel", name: "Mel", qty: 200, unit: "g" },
      { productKey: "egg", name: "Egg", qty: 3, unit: "stk" },
      { productKey: "smør", name: "Smør", qty: 100, unit: "g" },
      { productKey: "melk", name: "Melk", qty: 300, unit: "ml" },
      { productKey: "rømme", name: "Rømme", qty: 100, unit: "ml" },
    ],
  },
];

// Standard ukemeny (recipe IDs): man=1, tir=2, ons=3, tor=4, fre=5, lør=6, søn=7
const defaultMealPlan = [
  { dayOfWeek: 0, recipeId: 1, status: "planned" },
  { dayOfWeek: 1, recipeId: 2, status: "planned" },
  { dayOfWeek: 2, recipeId: 3, status: "planned" },
  { dayOfWeek: 3, recipeId: 4, status: "planned" },
  { dayOfWeek: 4, recipeId: 5, status: "planned" },
  { dayOfWeek: 5, recipeId: 6, status: "planned" },
  { dayOfWeek: 6, recipeId: 7, status: "planned" },
];

const chores = [
  { id: 1, task: "Støvsuge hus + hagestue", frequency: "ukentlig", defaultDay: 0, icon: "🧹", active: true },
  { id: 2, task: "Rydde huset inne", frequency: "ukentlig", defaultDay: 0, icon: "🏠", active: true },
  { id: 3, task: "Tørke støv", frequency: "14_dager", defaultDay: 1, icon: "✨", active: true },
  { id: 4, task: "Rydde hagestuen", frequency: "ukentlig", defaultDay: 1, icon: "🌿", active: true },
  { id: 5, task: "Skifte sengetøy", frequency: "14_dager", defaultDay: 2, icon: "🛏️", active: true },
  { id: 6, task: "Vaske det store badet", frequency: "ukentlig", defaultDay: 2, icon: "🚿", active: true },
  { id: 7, task: "Vaske det lille badet", frequency: "ukentlig", defaultDay: 3, icon: "🪥", active: true },
  { id: 8, task: "Ta ut søpla", frequency: "ukentlig", defaultDay: 3, icon: "🗑️", active: true, details: "Torsdag kveld – klar til fredag henting" },
  { id: 9, task: "Rydde i kjøleskapet", frequency: "ukentlig", defaultDay: 4, icon: "❄️", active: true },
  { id: 10, task: "Rydde ute (terrasse→garasje)", frequency: "14_dager", defaultDay: 4, icon: "🏡", active: true },
  { id: 11, task: "Pante flasker", frequency: "14_dager", defaultDay: 4, icon: "♻️", active: true },
  { id: 12, task: "Vaske tøy", frequency: "etter_behov", defaultDay: null, icon: "👕", active: true },
  { id: 13, task: "Rydding av kjøkken", frequency: "etter_behov", defaultDay: null, icon: "🍽️", active: true },
];

const consumables = [
  // === DRIKKEVARER ===
  { id: 1, name: "Zeroh saft", category: "Drikkevarer", depletionModel: "daily_rate", depletionRate: 500, depletionUnit: "ml/dag",
    currentQty: 0, unit: "ml", reorderThreshold: 500, autoAdd: true,
    packName: "Zeroh saft 1.5L", packSize: 1500, packUnit: "ml", estPrice: 35, store: "Kiwi Vågsbygd",
    notes: "5 glass à 200ml/kveld ≈ 500ml/dag. Halveres hvis brus kjøpes." },
  { id: 2, name: "Brus (diverse)", category: "Drikkevarer", depletionModel: "daily_rate", depletionRate: 500, depletionUnit: "ml/dag",
    currentQty: 0, unit: "ml", reorderThreshold: 1500, autoAdd: false,
    packName: "Brus 1.5L", packSize: 1500, packUnit: "ml", estPrice: 29, store: "Kiwi Vågsbygd",
    notes: "Manuelt — legg til når dere vil ha. Reduserer saftforbruk." },
  { id: 3, name: "Juice", category: "Drikkevarer", depletionModel: "daily_rate", depletionRate: 200, depletionUnit: "ml/dag",
    currentQty: 0, unit: "ml", reorderThreshold: 500, autoAdd: false,
    packName: "Appelsinjuice 1.5L", packSize: 1500, packUnit: "ml", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 4, name: "Kaffe (bønner)", category: "Drikkevarer", depletionModel: "fixed_interval", depletionRate: 14, depletionUnit: "dager/pose",
    currentQty: 0, unit: "poser", reorderThreshold: 1, autoAdd: true,
    packName: "Kaffebønner 500g", packSize: 1, packUnit: "pose", estPrice: 89, store: "Kiwi Vågsbygd",
    notes: "Siemens Eq300 bønnemaskin" },

  // === KJØKKEN ===
  { id: 5, name: "Bakepapir", category: "Kjøkken", depletionModel: "per_recipe_type", depletionRate: 1, depletionUnit: "ark/bruk",
    currentQty: 0, unit: "ark", reorderThreshold: 5, autoAdd: true,
    packName: "Bakepapir rull 30ark", packSize: 30, packUnit: "ark", estPrice: 25, store: "Kiwi Vågsbygd",
    notes: "1 ark per ovn/airfryer-rett" },
  { id: 6, name: "Aluminiumsfolie", category: "Kjøkken", depletionModel: "per_recipe_type", depletionRate: 0.5, depletionUnit: "ark/bruk",
    currentQty: 0, unit: "ark", reorderThreshold: 3, autoAdd: true,
    packName: "Aluminiumsfolie 20m", packSize: 20, packUnit: "ark", estPrice: 29, store: "Kiwi Vågsbygd" },
  { id: 7, name: "Fryseposer", category: "Kjøkken", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/eske",
    currentQty: 0, unit: "esker", reorderThreshold: 1, autoAdd: true,
    packName: "Fryseposer 3L 50stk", packSize: 1, packUnit: "eske", estPrice: 19, store: "Kiwi Vågsbygd" },
  { id: 8, name: "Matposer zip", category: "Kjøkken", depletionModel: "fixed_interval", depletionRate: 21, depletionUnit: "dager/eske",
    currentQty: 0, unit: "esker", reorderThreshold: 1, autoAdd: true,
    packName: "Zip-poser 1L 25stk", packSize: 1, packUnit: "eske", estPrice: 25, store: "Kiwi Vågsbygd" },
  { id: 9, name: "Oppvaskmiddel", category: "Kjøkken", depletionModel: "fixed_interval", depletionRate: 14, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Zalo oppvaskmiddel 500ml", packSize: 1, packUnit: "flaske", estPrice: 29, store: "Kiwi Vågsbygd" },
  { id: 10, name: "Oppvasktabletter", category: "Kjøkken", depletionModel: "daily_rate", depletionRate: 1, depletionUnit: "stk/dag",
    currentQty: 0, unit: "stk", reorderThreshold: 10, autoAdd: true,
    packName: "Oppvasktabletter 50stk", packSize: 50, packUnit: "stk", estPrice: 99, store: "Kiwi Vågsbygd" },
  { id: 11, name: "Kjøkkenrull", category: "Kjøkken", depletionModel: "fixed_interval", depletionRate: 7, depletionUnit: "dager/rull",
    currentQty: 0, unit: "ruller", reorderThreshold: 2, autoAdd: true,
    packName: "Kjøkkenrull 4-pk", packSize: 4, packUnit: "ruller", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 12, name: "Søppelposer", category: "Kjøkken", depletionModel: "fixed_interval", depletionRate: 3, depletionUnit: "dager/pose",
    currentQty: 0, unit: "poser", reorderThreshold: 5, autoAdd: true,
    packName: "Søppelposer 30L 20stk", packSize: 20, packUnit: "poser", estPrice: 29, store: "Kiwi Vågsbygd" },

  // === HUSHOLDNING (rengjøring/vask) ===
  { id: 13, name: "Toalettpapir", category: "Husholdning", depletionModel: "daily_rate", depletionRate: 0.5, depletionUnit: "ruller/dag",
    currentQty: 0, unit: "ruller", reorderThreshold: 4, autoAdd: true,
    packName: "Toalettpapir 12-pk", packSize: 12, packUnit: "ruller", estPrice: 69, store: "Kiwi Vågsbygd" },
  { id: 14, name: "Vaskemiddel tøy", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 21, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Vaskemiddel 1.5L", packSize: 1, packUnit: "flaske", estPrice: 79, store: "Kiwi Vågsbygd" },
  { id: 15, name: "Tøymykner", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 28, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Tøymykner 750ml", packSize: 1, packUnit: "flaske", estPrice: 49, store: "Kiwi Vågsbygd" },
  { id: 16, name: "Flekkfjerner", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 60, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Vanish flekkfjerner spray", packSize: 1, packUnit: "flaske", estPrice: 59, store: "Kiwi Vågsbygd" },
  { id: 17, name: "Baderomsspray", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 21, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Ajax baderom spray 750ml", packSize: 1, packUnit: "flaske", estPrice: 45, store: "Kiwi Vågsbygd" },
  { id: 18, name: "Allrengjøring", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 21, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Ajax allrengjøring 1.5L", packSize: 1, packUnit: "flaske", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 19, name: "Toalettrengjøring", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 14, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "WC-ent toalettrengjøring", packSize: 1, packUnit: "flaske", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 20, name: "Støvsugerposer", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 14, depletionUnit: "dager/pose",
    currentQty: 0, unit: "poser", reorderThreshold: 2, autoAdd: true,
    packName: "Støvsugerposer 4-pk", packSize: 4, packUnit: "poser", estPrice: 99, store: "Kiwi Vågsbygd",
    notes: "Sjekk modell — tilpass til egen støvsuger" },
  { id: 21, name: "Kluter/svamper", category: "Husholdning", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/pk",
    currentQty: 0, unit: "pakker", reorderThreshold: 1, autoAdd: false,
    packName: "Svamper 3-pk", packSize: 1, packUnit: "pk", estPrice: 25, store: "Kiwi Vågsbygd" },

  // === BARN (Mazie) ===
  { id: 22, name: "Bleier nyfødt", category: "Barn", depletionModel: "daily_rate", depletionRate: 9, depletionUnit: "stk/dag",
    currentQty: 0, unit: "stk", reorderThreshold: 30, autoAdd: true,
    packName: "Libero Newborn str.1 (28stk)", packSize: 28, packUnit: "stk", estPrice: 89, store: "Kiwi Vågsbygd",
    notes: "~9 bleier/dag for nyfødt. Justerer seg etter Mazie sitt behov." },
  { id: 23, name: "Våtservietter", category: "Barn", depletionModel: "daily_rate", depletionRate: 5, depletionUnit: "stk/dag",
    currentQty: 0, unit: "stk", reorderThreshold: 30, autoAdd: true,
    packName: "Libero våtservietter (64stk)", packSize: 64, packUnit: "stk", estPrice: 29, store: "Kiwi Vågsbygd",
    notes: "~5 stk/dag. Øker etter hvert som Mazie begynner med fast føde." },
  { id: 24, name: "Tåteflaske (reserve)", category: "Barn", depletionModel: "fixed_interval", depletionRate: 90, depletionUnit: "dager/stk",
    currentQty: 0, unit: "stk", reorderThreshold: 1, autoAdd: false,
    packName: "Philips Avent tåteflaske", packSize: 1, packUnit: "stk", estPrice: 129, store: "Coop Extra Vågsbygd" },
  { id: 25, name: "Smokk", category: "Barn", depletionModel: "fixed_interval", depletionRate: 60, depletionUnit: "dager/stk",
    currentQty: 0, unit: "stk", reorderThreshold: 1, autoAdd: false,
    packName: "Smokk 0-6 mnd 2-pk", packSize: 2, packUnit: "stk", estPrice: 79, store: "Coop Extra Vågsbygd" },
  { id: 26, name: "Babysåpe/vask", category: "Barn", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Barnängen babysåpe 250ml", packSize: 1, packUnit: "flaske", estPrice: 49, store: "Kiwi Vågsbygd" },
  { id: 27, name: "Sinksalve", category: "Barn", depletionModel: "fixed_interval", depletionRate: 45, depletionUnit: "dager/tube",
    currentQty: 0, unit: "tuber", reorderThreshold: 1, autoAdd: true,
    packName: "Bepanthen sinksalve 100g", packSize: 1, packUnit: "tube", estPrice: 119, store: "Apotek",
    notes: "Forebygger bleierutslett" },
  { id: 28, name: "Morsmelkerstatning", category: "Barn", depletionModel: "daily_rate", depletionRate: 100, depletionUnit: "g/dag",
    currentQty: 0, unit: "g", reorderThreshold: 200, autoAdd: false,
    packName: "NAN 1 morsmelkerstatning 800g", packSize: 800, packUnit: "g", estPrice: 199, store: "Kiwi Vågsbygd",
    notes: "Kun om amming ikke dekker. Deaktivert til det evt. trengs." },

  // === PERSONLIG PLEIE ===
  { id: 29, name: "Shampoo Christer", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Shampoo 400ml", packSize: 1, packUnit: "flaske", estPrice: 49, store: "Kiwi Vågsbygd" },
  { id: 30, name: "Shampoo Martine", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Shampoo 400ml", packSize: 1, packUnit: "flaske", estPrice: 59, store: "Kiwi Vågsbygd" },
  { id: 31, name: "Balsam Martine", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Balsam 400ml", packSize: 1, packUnit: "flaske", estPrice: 59, store: "Kiwi Vågsbygd" },
  { id: 32, name: "Dusjsåpe", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 21, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Dusjsåpe 400ml", packSize: 1, packUnit: "flaske", estPrice: 35, store: "Kiwi Vågsbygd" },
  { id: 33, name: "Tannkrem", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 45, depletionUnit: "dager/tube",
    currentQty: 0, unit: "tuber", reorderThreshold: 1, autoAdd: true,
    packName: "Tannkrem 75ml", packSize: 1, packUnit: "tube", estPrice: 35, store: "Kiwi Vågsbygd" },
  { id: 34, name: "Tannbørster", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 90, depletionUnit: "dager/stk",
    currentQty: 0, unit: "stk", reorderThreshold: 1, autoAdd: false,
    packName: "Tannbørste 2-pk", packSize: 2, packUnit: "stk", estPrice: 49, store: "Kiwi Vågsbygd" },
  { id: 35, name: "Deodorant Christer", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 45, depletionUnit: "dager/stk",
    currentQty: 0, unit: "stk", reorderThreshold: 1, autoAdd: true,
    packName: "Deodorant", packSize: 1, packUnit: "stk", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 36, name: "Deodorant Martine", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 45, depletionUnit: "dager/stk",
    currentQty: 0, unit: "stk", reorderThreshold: 1, autoAdd: true,
    packName: "Deodorant", packSize: 1, packUnit: "stk", estPrice: 39, store: "Kiwi Vågsbygd" },
  { id: 37, name: "Intimsåpe Dr. Greve", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 60, depletionUnit: "dager/flaske",
    currentQty: 0, unit: "flasker", reorderThreshold: 1, autoAdd: true,
    packName: "Dr. Greve intimsåpe 200ml", packSize: 1, packUnit: "flaske", estPrice: 59, store: "Kiwi Vågsbygd" },
  { id: 38, name: "Bind/tamponger", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 28, depletionUnit: "dager/pk",
    currentQty: 0, unit: "pakker", reorderThreshold: 1, autoAdd: true,
    packName: "Libresse 14-pk", packSize: 1, packUnit: "pk", estPrice: 45, store: "Kiwi Vågsbygd" },
  { id: 39, name: "Barberhøvel/blader", category: "Personlig pleie", depletionModel: "fixed_interval", depletionRate: 30, depletionUnit: "dager/pk",
    currentQty: 0, unit: "pakker", reorderThreshold: 1, autoAdd: false,
    packName: "Gilette blader 4-pk", packSize: 1, packUnit: "pk", estPrice: 89, store: "Kiwi Vågsbygd" },
];

// Hvilke alternative oppskrifter passer til hvilken dag (basert på kategori og ingrediensoverlapp)
const altSuggestionMap = {
  0: [8, 9, 19, 31, 35],     // Mandag: raske kylling/curry-alt
  1: [13, 14, 15, 28, 33],   // Tirsdag: fisk-alternativer
  2: [10, 26, 21, 24, 34],   // Onsdag: raske diverse
  3: [11, 12, 19, 31, 35],   // Torsdag: raske diverse
  4: [17, 18, 22, 25, 16],   // Fredag: comfort food
  5: [20, 23, 27, 29, 36],   // Lørdag: helg-retter
  6: [30, 32, 27, 20, 23],   // Søndag: helg langtid
};

function getWeekYear(date) {
  const d = date || new Date();
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil((((d - yearStart) / 86400000) + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(weekNo).padStart(2, '0')}`;
}

module.exports = { products, recipes, defaultMealPlan, chores, consumables, altSuggestionMap, getWeekYear };
