// @ts-check
/**
 * Week 9 SAF-1: deterministic allergy post-filter for LLM-generated recipes.
 *
 * This file is the only place in the codebase that provides a "SAFETY"
 * guarantee against allergy violations. LLM output (recipes generated by
 * Ollama/OpenAI/Anthropic) is NOT trusted — the LLM can hallucinate, forget
 * allergies in context, or use wrong ingredient names. This file catches that.
 *
 * Model:
 *   1. Operator registers allergies in family_profile (list of strings).
 *   2. This service expands each allergy into a "trigger synonym list" via
 *      ALLERGY_TRIGGERS (e.g. "nøtter" → nøtt, hasselnøtt, peanøtt, mandel,
 *      valnøtt, cashew, pistasj, etc.).
 *   3. For every ingredient in the recipe the name is checked against the
 *      trigger list via lowercase substring match (simple, deterministic,
 *      no AI).
 *   4. The recipe receives the flags:
 *        - safeForProfile: boolean
 *        - blockedIngredients: [{ingredient, allergy, trigger}]
 *   5. Frontend shows a clear warning when safeForProfile=false.
 *
 * Design choices:
 *   - No fuzzy matching, no LLM, no probabilistic logic. Substring match is
 *     deliberately strict — false positives are acceptable (too many warnings
 *     is better than one missed allergen).
 *   - Trigger list is conservative: "nøtter" matches anything containing
 *     "nøt" including "muskatnøtt" (safe) and "nøttebrun" (false positive).
 *     For false positives the operator can override in the UI.
 *   - Each trigger entry is an Array<string> to allow multiple synonyms.
 *   - Supplement list for "hidden" allergens (lactose in wheat-free pasta
 *     is still lactose if the recipe contains "parmesan").
 */

/**
 * Norwegian allergy triggers. Keys are lowercase synonyms for user input,
 * values are lists of ingredient substrings that trigger a match.
 * ALL MATCHING IS CASE-INSENSITIVE.
 *
 * @type {Record<string, string[]>}
 */
const ALLERGY_TRIGGERS = {
  // Nuts — broad category
  nøtter: [
    'nøtt',
    'nott',
    'hasselnøtt',
    'hasselnott',
    'peanøtt',
    'peanott',
    'mandel',
    'mandle',
    'valnøtt',
    'valnott',
    'cashew',
    'pistasj',
    'paranøtt',
    'paranott',
    'pekannøtt',
    'pekannott',
    'macadamia',
    'pine nut',
    'pinjekjerne',
  ],
  peanøtter: ['peanøtt', 'peanott', 'peanut', 'jordnøtt', 'jordnott'],
  mandler: ['mandel', 'mandle', 'almond'],
  hasselnøtter: ['hasselnøtt', 'hasselnott', 'hazelnut'],

  // Milk / lactose
  laktose: [
    'melk',
    'fløte',
    'flote',
    'rømme',
    'romme',
    'smør',
    'smor',
    'ost',
    'yoghurt',
    'parmesan',
    'mozzarella',
    'cheddar',
    'feta',
    'ricotta',
    'krem',
    'kondensert melk',
    'myse',
    'whey',
    'kasein',
  ],
  melk: [
    'melk',
    'fløte',
    'flote',
    'rømme',
    'romme',
    'smør',
    'smor',
    'ost',
    'yoghurt',
    'parmesan',
    'mozzarella',
    'cheddar',
    'feta',
    'ricotta',
    'krem',
    'myse',
    'whey',
    'kasein',
  ],

  // Gluten
  gluten: [
    'hvete',
    'hvetemel',
    'mel', // NOTE: false positive on e.g. 'rismel'
    'rug',
    'bygg',
    'spelt',
    'kamut',
    'couscous',
    'semolina',
    'bulgur',
    'pasta',
    'nudler',
    'brød',
    'tortilla',
    'kornblanding',
    'kjeks',
    'seitan',
    'farris',
    'tarrinne',
  ],
  hvete: ['hvete', 'hvetemel', 'semolina', 'couscous', 'bulgur', 'spelt', 'kamut', 'pasta', 'brød'],

  // Egg
  egg: ['egg', 'eggehvite', 'eggeplomme', 'eggerøre', 'omelett', 'majones'],

  // Shellfish
  skalldyr: [
    'reke',
    'reker',
    'krabbe',
    'hummer',
    'kreps',
    'blåskjell',
    'blaskjell',
    'østers',
    'osters',
    'kamskjell',
    'akkar',
    'blekksprut',
  ],

  // Fish
  fisk: [
    'fisk',
    'laks',
    'torsk',
    'sei',
    'tunfisk',
    'tuna',
    'makrell',
    'sild',
    'hyse',
    'kveite',
    'rødspette',
    'rodspette',
    'uer',
    'steinbit',
    'ansjos',
    'sardin',
    'kaviar',
  ],

  // Soy
  soya: ['soya', 'soyasaus', 'tofu', 'edamame', 'miso', 'tempeh'],

  // Sesame
  sesam: ['sesam', 'tahini'],

  // Mustard
  sennep: ['sennep', 'dijon', 'mustard'],

  // Celery
  selleri: ['selleri', 'sellerirot', 'celery'],

  // Lupin
  lupin: ['lupin'],

  // Sulfur dioxide / sulfites
  sulfitter: ['sulfitt', 'sulfitter', 'vin', 'tørket frukt', 'torket frukt'],
};

/**
 * Normalise the allergy string to a canonical key that matches
 * ALLERGY_TRIGGERS. Strips hyphens and edge whitespace, lowercases.
 *
 * @param {string} allergy
 * @returns {string}
 */
function normalizeAllergyKey(allergy) {
  if (typeof allergy !== 'string') return '';
  return allergy.toLowerCase().trim().replace(/-/g, '').replace(/\s+/g, ' ');
}

/**
 * Build the merged trigger list for ALL allergies the user has.
 * Returns a Map from trigger substring to which allergy generated it.
 *
 * @param {string[]} allergies
 * @returns {Map<string, string>} trigger-substring → allergy name
 */
function buildTriggerMap(allergies) {
  /** @type {Map<string, string>} */
  const map = new Map();
  if (!Array.isArray(allergies)) return map;

  for (const rawAllergy of allergies) {
    const key = normalizeAllergyKey(rawAllergy);
    if (!key) continue;

    // Match all trigger keys that contain the allergy (or vice versa).
    // This catches "nøtt" → ALLERGY_TRIGGERS['nøtter'], "peanøtter" → own key.
    const foundDirect = ALLERGY_TRIGGERS[key];
    if (foundDirect) {
      for (const t of foundDirect) {
        map.set(t.toLowerCase(), rawAllergy);
      }
      continue;
    }

    // Fuzzy: if the user's allergy string contains one of the trigger keys,
    // or vice versa, use the triggers. E.g. "melkeprotein" → 'melk'.
    for (const [triggerKey, triggerList] of Object.entries(ALLERGY_TRIGGERS)) {
      if (key.includes(triggerKey) || triggerKey.includes(key)) {
        for (const t of triggerList) {
          map.set(t.toLowerCase(), rawAllergy);
        }
      }
    }

    // Fallback: use the allergy string itself as a trigger
    map.set(key, rawAllergy);
  }

  return map;
}

/**
 * @typedef {object} BlockedIngredient
 * @property {string} ingredient - Original ingredient name from the recipe
 * @property {string} allergy - Which user allergy was violated
 * @property {string} trigger - Substring that matched
 */

/**
 * @typedef {object} AllergyCheckResult
 * @property {boolean} safeForProfile
 * @property {BlockedIngredient[]} blockedIngredients
 * @property {string[]} checkedAgainst - Allergies used in the check
 */

/**
 * Check a recipe against a user profile.
 *
 * @param {{ingredients?: Array<{name?: string, ingredient?: string}>}} recipe
 * @param {{allergies?: string[]}} profile
 * @returns {AllergyCheckResult}
 */
function checkRecipe(recipe, profile) {
  const allergies = (profile?.allergies || []).filter((a) => typeof a === 'string' && a.trim());

  // Empty allergies → everything is safe (no profile = no protection)
  if (allergies.length === 0) {
    return { safeForProfile: true, blockedIngredients: [], checkedAgainst: [] };
  }

  const triggerMap = buildTriggerMap(allergies);

  /** @type {BlockedIngredient[]} */
  const blocked = [];
  const ingredients = recipe?.ingredients || [];

  for (const ing of ingredients) {
    const rawName = (ing && (ing.name || ing.ingredient)) || '';
    if (typeof rawName !== 'string' || !rawName.trim()) continue;
    const lower = rawName.toLowerCase();

    for (const [trigger, allergy] of triggerMap.entries()) {
      if (lower.includes(trigger)) {
        blocked.push({
          ingredient: rawName,
          allergy,
          trigger,
        });
        // Break inner — only the first match per ingredient (avoid duplicates)
        break;
      }
    }
  }

  return {
    safeForProfile: blocked.length === 0,
    blockedIngredients: blocked,
    checkedAgainst: allergies,
  };
}

/**
 * Batch-check several recipes at once (e.g. before showing
 * recipe suggestions in meal planning).
 *
 * @param {Array<{ingredients?: Array<{name?: string, ingredient?: string}>}>} recipes
 * @param {{allergies?: string[]}} profile
 * @returns {Array<AllergyCheckResult>}
 */
function checkRecipes(recipes, profile) {
  if (!Array.isArray(recipes)) return [];
  return recipes.map((r) => checkRecipe(r, profile));
}

/**
 * Decorate a recipe with safety fields. Returns a copy with
 * safeForProfile + blockedIngredients added.
 *
 * @param {object} recipe
 * @param {{allergies?: string[]}} profile
 * @returns {object}
 */
function annotateRecipe(recipe, profile) {
  const check = checkRecipe(/** @type {any} */ (recipe), profile);
  return Object.assign({}, recipe || {}, check);
}

// ============================================================
// B7 — Per-member allergy check (D7 lag 1: HARDT filter)
// ============================================================
//
// Same deterministic substring-match as checkRecipe(), but extended to
// carry per-member attribution. Every blocked ingredient now records
// WHICH members are affected (blockedFor: string[]) so the UI can say
// "Inneholder gluten — truer Lise, Kari".
//
// Fallback semantics (D6 fallback-arv): a member with allergies=null
// inherits familyAllergies. A member with allergies=[] explicitly
// has no allergies (does NOT fall back). Same logic for dislikes.
//
// safeForFamily is false if any member has at least one blocked
// ingredient — allergy is a HARD filter per D7 (no override).

/**
 * @typedef {object} FamilyMemberContext
 * @property {number} id
 * @property {string} name
 * @property {string[]|null} [allergies] - null = inherit familyAllergies
 * @property {string[]|null} [dislikes] - null = inherit familyDislikes
 * @property {string[]} [dietTags]
 * @property {string|null} [customDietNote]
 */

/**
 * @typedef {object} FamilyContext
 * @property {string[]} familyAllergies - family_profile.allergies
 * @property {string[]} familyDislikes - family_profile.dislikes
 * @property {FamilyMemberContext[]} members
 */

/**
 * @typedef {object} PerMemberBlockedIngredient
 * @property {string} ingredient
 * @property {string} allergy
 * @property {string} trigger
 * @property {string[]} blockedFor - Names of members whose allergies were hit
 */

/**
 * @typedef {object} PerMemberAllergyResult
 * @property {boolean} safeForFamily
 * @property {PerMemberBlockedIngredient[]} blockedIngredients
 * @property {string[]} effectiveAllergies - Union across all members
 */

function effectiveAllergiesForMember(member, familyAllergies) {
  // null = inherit, [] = explicit empty, array = own list
  if (member.allergies === null || member.allergies === undefined) {
    return Array.isArray(familyAllergies) ? familyAllergies : [];
  }
  return Array.isArray(member.allergies) ? member.allergies : [];
}

/**
 * Check a recipe against a family context (per-member allergies).
 *
 * @param {{ingredients?: Array<{name?: string, ingredient?: string}>}} recipe
 * @param {FamilyContext} familyContext
 * @returns {PerMemberAllergyResult}
 */
function checkRecipeForFamily(recipe, familyContext) {
  const fa = Array.isArray(familyContext?.familyAllergies) ? familyContext.familyAllergies : [];
  const members = Array.isArray(familyContext?.members) ? familyContext.members : [];

  // Per-member trigger maps: Map<triggerSubstring, Set<memberName>>.
  // Also collect the union for effectiveAllergies.
  /** @type {Map<string, { allergy: string, members: Set<string> }>} */
  const triggerByMember = new Map();
  const unionAllergies = new Set();

  // If no members, fall back to family-level for a single virtual "family" member.
  // This matches the backward-compat behavior where checkRecipe(recipe, { allergies: [...] })
  // treats the family as a single entity.
  const effectiveMembers =
    members.length > 0
      ? members.map((m) => ({
          name: m.name || 'Unknown',
          effective: effectiveAllergiesForMember(m, fa),
        }))
      : [{ name: 'familie', effective: fa }];

  for (const m of effectiveMembers) {
    for (const a of m.effective) {
      if (typeof a !== 'string' || !a.trim()) continue;
      unionAllergies.add(a);
    }
    const memberMap = buildTriggerMap(m.effective);
    for (const [trigger, allergy] of memberMap.entries()) {
      if (!triggerByMember.has(trigger)) {
        triggerByMember.set(trigger, { allergy, members: new Set() });
      }
      triggerByMember.get(trigger).members.add(m.name);
    }
  }

  /** @type {PerMemberBlockedIngredient[]} */
  const blocked = [];
  const ingredients = recipe?.ingredients || [];

  for (const ing of ingredients) {
    const rawName = (ing && (ing.name || ing.ingredient)) || '';
    if (typeof rawName !== 'string' || !rawName.trim()) continue;
    const lower = rawName.toLowerCase();

    for (const [trigger, { allergy, members: affected }] of triggerByMember.entries()) {
      if (lower.includes(trigger)) {
        blocked.push({
          ingredient: rawName,
          allergy,
          trigger,
          blockedFor: Array.from(affected).sort(),
        });
        break; // one match per ingredient
      }
    }
  }

  return {
    safeForFamily: blocked.length === 0,
    blockedIngredients: blocked,
    effectiveAllergies: Array.from(unionAllergies),
  };
}

module.exports = {
  ALLERGY_TRIGGERS,
  normalizeAllergyKey,
  buildTriggerMap,
  checkRecipe,
  checkRecipes,
  annotateRecipe,
  // B7 — per-member API
  checkRecipeForFamily,
  effectiveAllergiesForMember,
};
